name: Ubuntu Setup

on:
  workflow_dispatch:

jobs:
  setup-tailscale-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Cài đặt SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          sudo systemctl status ssh --no-pager

      - name: Cài đặt Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Đăng nhập Tailscale với token
        run: |
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_TOKEN }} --ssh

      - name: Hiển thị địa chỉ Tailscale SSH
        run: |
          echo "Tailscale IP (IPv4):"
          tailscale ip -4
          echo "Tailscale IP (IPv6):"
          tailscale ip -6
          echo "SSH user mặc định: runner"
          echo "ssh runner@<tailscale-ip>"

      - name: Giữ runner sống trong 6 giờ (bằng cách spam log)
        run: |
          echo "Giữ runner sống trong tối đa 6 giờ (CTRL+C để dừng nếu cần)"
          end=$((SECONDS+21600))  # 6 tiếng = 21600 giây
          while [ $SECONDS -lt $end ]; do
            echo "Runner vẫn đang hoạt động... $(date)"
            sleep 300  # Mỗi 5 phút in 1 lần
          done
