name: Check System Configuration

on:
  workflow_dispatch:

jobs:
  check-system:
    runs-on: ubuntu-22.04
    steps:
      - name: Show CPU Info
        run: lscpu

      - name: Show RAM Info
        run: free -h

      - name: Show Disk Info
        run: lsblk
